# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.migrations.operations.special
from django.utils.timezone import utc


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# core.migrations.0004_holding_created
# core.migrations.0006_holding_updated

class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20160504_1257'), ('core', '0003_holding_created_date'), ('core', '0004_holding_created'), ('core', '0005_remove_holding_created_date'), ('core', '0006_holding_updated')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('subregister', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('security', models.CharField(max_length=255)),
                ('holding', models.PositiveIntegerField()),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('close_price_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 12, 23, 57, 48, 864381, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 18, 11, 42, 8, 950237, tzinfo=utc))),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('security', 'close_price_date')]),
        ),
        migrations.RemoveField(
            model_name='holding',
            name='created_date',
        ),
        migrations.AddField(
            model_name='holding',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 18, 12, 23, 26, 290241, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
