# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('subregister', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('security', models.CharField(max_length=255)),
                ('holding', models.PositiveIntegerField()),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('close_price_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
