# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0006_holding_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
