# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('security', 'close_price_date')]),
        ),
    ]
