# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160504_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 12, 23, 57, 48, 864381, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
