# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160518_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'verbose_name': 'holding entry', 'verbose_name_plural': 'holding entries'},
        ),
    ]
