# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 12:23
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.db.models import F
from django.utils.timezone import utc

from core.models import Holding


def forwards(apps, schema_editor):
    """Copy the value of created field to updated field"""

    Holding.objects.update(updated=F('created'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_holding_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='updated',
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(2016, 5, 18, 12, 23, 26, 290241, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
